apiVersion: apps/v1
kind: Deployment 
metadata:
  annotations:
  labels:
    app: springpetclinic
    app.kubernetes.io/component: springpetclinic
    app.kubernetes.io/instance: springpetclinic
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: springpetclinic
    app.openshift.io/runtime: java
  name: springpetclinic
  namespace: springpetclinichelm
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: springpetclinic
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: springpetclinic
          deploymentconfig: springpetclinic
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/springpetclinichelm/springpetclinic:latest
          imagePullPolicy: Always
          name: springpetclinic
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
